### ISSUE TITLE
Comparison with CompositeAndroid

### ISSUE THREAD

**Issue by passsy** [beworker/featured#1]
Did you know about my [CompositeAndroid](https://github.com/passsy/CompositeAndroid) library? Could you comment on benefits of `featured`?

This is what I came up after a fist look:
### featured Pros:
- performance is slightly faster, only used methods get called
- custom methods with custom parameters
### featured Cons:
- `FeatureHost` has to be called manually which is error prone
- Features can be shared in a library but require manually binding of all methods of the Activity (and the instructions when those methods have to be called; before or after `super`)
- limited on the main thread

**Comment by sergejsha** [comment]
Hey Pascal, I didn't know anything about CompositeAndroid, but I've just quickly checked it out. 

I do not really consider the points you mentioned as 'cons' to be 'cons' because, in my opinion, there must be no necessary magic in the library. It already magically generates all needed dispatch methods and it was a conscious decision to ask client calling these callbacks explicitly when _client_ needs it. Featured is very different from CompositeAndroid in that respect. It is not bound to any framework's classes like Activity or Fragment classes and doesn't require any special inheritance. It just generates dispatch-methods for any events with any parameters. For example you can easily defined custom `onCreate()` method with any parameters, which is very convenient. You can even add new lifecycle events like `onBooksOpen(Book book)` and `onBookClosed(Book book)` or  `GoogleApiClient`  callbacks etc.

Because of this flexibility and decoupling you can reuse same feature host in any activity or fragment. In my recent project we even reused our feature host with its sub-set of features in a service and it worked very well. 

If you use same base feature class, you can even reuse same features in different projects. I have even used features as fragment extension API, allowing client to extend fragment's functionality by implementing feature-based API.

Main thread limitation is not a limitation of design, but rather a limitation of the first implementation. There was no requirements for supporting multithreading, that's why I simply implemented a "require Main Thread" strategy. It is fairly easy to extend it with any async processing, because event dispatching is already done in async manner. Just matter of necessity and time.

Another benefit is the ability to enable, disable or replace features depending on device configuration. For instance, we have same feature implemented for different Android versions. Thus when we create a feature host we just instantiate the right feature. It gives us a very clean implementation without configuration specific if-else logic inside the feature.

If you think about feature-concept closely, you will find endless list of cases where splitting code into separate features would be very beneficial.
