### ISSUE TITLE
Question about the context

### ISSUE THREAD

**Issue by MFlisar** [beworker/featured#2]
Why is the `FeatureHost` needing a context? Is it just for convenience?

If I'm right, it's save to pass the application context as context (if I don't need the context in my class).

**Comment by sergejsha** [comment]
As for now, this is just a convenience for features. Instead of giving features context via constructor features can use context of feature host. It's safe to pass application context in there.

Now I am working on an update where context type will be a parameter, meaning you will be able to use any type and not just `android.content.Context`. Since new update context type will be a part of Feature contract. It means your features can define which type of context they can work with. This will make feature contract even more strict.

**Comment by MFlisar** [comment]
So the `@NonNull` of the context is there by accident, because it does not really need a context currently?

I just found this problem because I'm trying out https://github.com/bluelinelabs/Conductor and I wanted to log lifecycle events and constructor events via a feature...

**Comment by sergejsha** [comment]
It will thing of making it optional. For now it is required because this is the only what a feature can access context and you can give it application instance.

**Comment by MFlisar** [comment]
That answers my question. Actually, you can pass null as a context as well...
