### ISSUE TITLE
Feature with default functions

### ISSUE THREAD

**Issue by MFlisar** [beworker/featured#3]
Is it possible to create a Feature that does more than delegation? Something like following would be nice:

```
public ExampleFeature extends Feature<ExampleFeatureHost>
{
private int mLevel = 0;

@FeatureEvent
protected int getLevel() { return mLevel; }

@FeatureEvent
protected void goToLevel(int level) { }
}
```

Currently, if I need synchronous functions, I have to implement them in the base class that holds the feature (like the activity for example). Is there any other way to do this?

**Comment by sergejsha** [comment]
Feature is event based by design. It implements logic for asynchronous event processing. That's why event methods cannot return any result.

The code above won't compile because of `getLevel()` method returning integer. To make it compilable you should either return `void` or remove `@FeatureEvent` annotation from the method. Not sure whether this helps you with the logic you want to implement though.

**Comment by MFlisar** [comment]
I wanted to handle a state that's common to two features via a base feature... After playing around a little bit I see it's better to just pass the common parent object to the feature...
