### ISSUE TITLE
Reusage of Feature

### ISSUE THREAD

**Issue by MFlisar** [beworker/featured#5]
I'm using a single activity with view based navigation (with the help of https://github.com/bluelinelabs/Conductor)

This means, I create controller classes (actually a view) that are added/removed to the activity, depedning on the current state. This controllers have their own lifecycle like events like `onCreate` and `onDestroy` for example. Therefore they all have their own `LifecycleFeatureHost` (a simple feature, that just does something in `onCreate` and `onDestroy` to make it easier) to which they add their own features (logger feature, toolbar feature and similar).

When using features like that, I'm somehow lost, when I want to dispatch an event, because I have to iterate over all existing `LifecylceFeatureHosts`. This means manually keeping track on them... Because if I dispatch an event, I want that all currently existing controllers get the event.

Any ideas on that?

My idea is following:

It should be possible to add/remove features to a host... This way, I could create one `LifecycleFeatureHost` in my activity (or even use a singleton) and pass it to my controllers, then they add their own features when necessary and remove them again when necessary. Every controller can then dispatch an event and all other controllers will receive this event as well, if they are currently registered at the host.

Simply adding following to the `FeatureHost` should do it:

```
public void add(F feature) {
    Class<F> clazz = (Class<F>) feature.getClass();
    if (mFeatures.containsKey(clazz)) {
        throw new IllegalArgumentException(
                String.format("Feature %s is already registered", clazz));
    }
    mFeatures.put(clazz, feature);
    feature.attachFeatureHost(this);
}

public boolean remove(F feature) {
    Class<F> clazz = (Class<F>) feature.getClass();
    F f = mFeatures.remove(clazz)) ;
    return f != null;
}
```

What do you say? Does anything speak against that? It's limited though, as you can't register features of one class multiple times, but that's of for my use case... I would have an idea to solve that though as well. But I'm waiting for your response, maybe there is a big reason that speaks against this all...

_Edit_

As the features are currently bound to the main thread, it probably makes sense to make sure, the add/remove functions are called on the main thread as well

**Comment by MFlisar** [comment]
I'm testing this out and I would make a pull request afterwards, if you like this idea and don't see any problems...

**Comment by sergejsha** [comment]
I didn't use conductor before, but just looked into the lifecycle docs and demo app. As far as I can see, each controller (as defined by conductor) has the same lifecycle: `onCreateView()`, `onAttach()`, controller in focus, `onDetach()`, `onDestroyView()`, `onDestroy()`. 

Now, as you described, we can decompose controller's code into smaller features. For that I would also define a `ControllerFeature` reflecting original controller lifecycle. Then I would implement a generic `FeaturedController` class with a `ControllerFeatureHost` field. `FeaturedController` should forward events to its own `ControllerFeatureHost` host. All other controllers should extend the `FeaturedController` class. If designed like this, all your features will receive lifecycle events "automatically". You don't need to iterate through all feature hosts then, because controllers will receive lifecycle events and dispatch them to their feature hosts.

Am I right or do I miss something?

**Comment by MFlisar** [comment]
That sounds good as well. I thought about something similar too but then I thought a add/remove function is so easy and flexible...

I actually don't really need shared life cycle events but more some extra events to share events between my controllers. I use it currently like an activity internal bus... one controller has a menu and if an item is selected this is event is dispatched and another controller has overwritten the dispatching method and handles the event  (or even more controllers). Another example is a filter event in on controller... which updates another one.

Your suggestion works as well as far as I see. But still, why are you restricting following:
- only one feature per class
- no add/remove functions for features

Are there any reasons for that?

**Comment by MFlisar** [comment]
Thinking about it again I think you miss a point. I had what you suggest. The problem is I don't want shared life cycle events but some manually dispatched events.

So one controller dispatches an event and I want to receive this event in another controller (or even in more other controllers).

With a Base controller like you suggest all controllers have their own feature host and therefore I can't dispatch and event to all hosts directly...

**Comment by sergejsha** [comment]
I suspected you had an issue with additional custom events, which do not belong to the controller lifecycle. There is no built-in solution for this use case, because it is a mixed case, where lifecycle of controllers is mixed with lifecycle of another component sending those customer events. This is rather an event bus use case (fire and forget). Featured forces a bit most strict design. That's why it is not an event bus. 

Nevertheless you can solve it with featured as well. I would do it like this. I would create an `EventProxyFeature` with `addFeatureHost()` and `removeFeatureHost()` methods. All this feature does when receiving an event is to dispatch that event further to the kept feature hosts. Then your `FeaturedController` has to somehow register/unregister its feature host at that `EventProxyFeature`. Now you can create another feature host with a single `EventProxyFeature` and dispatch all custom events though that feature host. The events will be forwarded to all other features automatically.

Hope this helps.

**Comment by MFlisar** [comment]
Thanks for the explanation. Actually you're right, I was trying to implement an event bus that is not completely loosely coupled...

After trying around and seeing how it works in the end, I'll stay with the RXBus I've created.
